version: '2'
services:
  jenkins:
    image: laig/docker-jenkins:latest
    container_name: jenkins
    user: jenkins
    volumes:
      - C:/docker/Jenkins/jenkins-data:/var/jenkins_home
      - C:/docker/Jenkins/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
